# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='person',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='due_to',
        ),
        migrations.AddField(
            model_name='audio',
            name='url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
