# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_auto_20170417_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
